export const DIVISAS = [
  // Principales
  { code: 'EUR', label: 'EUR - EURO', symbol: '€', decimal: ',', separator: '.' },
  { code: 'USD', label: 'USD - DÓLAR AMERICANO', symbol: '$', decimal: '.', separator: ',' },
  { code: 'GBP', label: 'GBP - LIBRA ESTERLINA', symbol: '£', decimal: '.', separator: ',' },
  { code: 'JPY', label: 'JPY - YEN JAPONÉS', symbol: '¥', decimal: '.', separator: ',', precision: 0 },
  { code: 'CHF', label: 'CHF - FRANCO SUIZO', symbol: 'CHF ', decimal: '.', separator: "'" },
  { code: 'CAD', label: 'CAD - DÓLAR CANADIENSE', symbol: 'CA$', decimal: '.', separator: ',' },
  { code: 'AUD', label: 'AUD - DÓLAR AUSTRALIANO', symbol: 'A$', decimal: '.', separator: ',' },
  // Europa
  { code: 'DKK', label: 'DKK - CORONA DANESA', symbol: 'kr', decimal: ',', separator: '.' },
  { code: 'SEK', label: 'SEK - CORONA SUECA', symbol: 'kr', decimal: ',', separator: '.' },
  { code: 'NOK', label: 'NOK - CORONA NORUEGA', symbol: 'kr', decimal: ',', separator: '.' },
  { code: 'ISK', label: 'ISK - CORONA ISLANDESA', symbol: 'kr', decimal: ',', separator: '.', precision: 0 },
  { code: 'PLN', label: 'PLN - ESLOTI POLACO', symbol: 'zł', decimal: ',', separator: '.' },
  { code: 'CZK', label: 'CZK - CORONA CHECA', symbol: 'Kč', decimal: ',', separator: '.' },
  { code: 'HUF', label: 'HUF - FORINTO HÚNGARO', symbol: 'Ft', decimal: ',', separator: '.', precision: 0 },
  { code: 'BGN', label: 'BGN - LEV BÚLGARO', symbol: 'лв', decimal: ',', separator: '.' },
  { code: 'RON', label: 'RON - LEU RUMANO', symbol: 'lei', decimal: ',', separator: '.' },
  { code: 'UAH', label: 'UAH - HRYVNIA UCRANIANA', symbol: '₴', decimal: ',', separator: '.' },
  { code: 'TRY', label: 'TRY - LIRA TURCA', symbol: '₺', decimal: ',', separator: '.' },
  { code: 'ALL', label: 'ALL - LEK ALBANÉS', symbol: 'L', decimal: ',', separator: '.' },
  { code: 'BAM', label: 'BAM - MARCO CONVERTIBLE BOSNIO', symbol: 'KM', decimal: ',', separator: '.' },
  { code: 'BYN', label: 'BYN - RUBLO BIELORRUSO', symbol: 'Br', decimal: ',', separator: '.' },
  { code: 'GIP', label: 'GIP - LIBRA GIBRALTAREÑA', symbol: '£', decimal: '.', separator: ',' },
  { code: 'MKD', label: 'MKD - DENAR MACEDONIO', symbol: 'ден', decimal: ',', separator: '.' },
  { code: 'RUB', label: 'RUB - RUBLO RUSO', symbol: '₽', decimal: ',', separator: '.' },
  { code: 'RSD', label: 'RSD - DINAR SERBIO', symbol: 'дин.', decimal: ',', separator: '.' },
  // Latinoamérica y Caribe
  { code: 'MXN', label: 'MXN - PESO MEXICANO', symbol: '$', decimal: '.', separator: ',' },
  { code: 'BRL', label: 'BRL - REAL BRASILEÑO', symbol: 'R$', decimal: ',', separator: '.' },
  { code: 'ARS', label: 'ARS - PESO ARGENTINO', symbol: '$', decimal: ',', separator: '.' },
  { code: 'COP', label: 'COP - PESO COLOMBIANO', symbol: '$', decimal: ',', separator: '.' },
  { code: 'CLP', label: 'CLP - PESO CHILENO', symbol: '$', decimal: ',', separator: '.', precision: 0 },
  { code: 'PEN', label: 'PEN - SOL PERUANO', symbol: 'S/', decimal: '.', separator: ',' },
  { code: 'UYU', label: 'UYU - PESO URUGUAYO', symbol: '$U', decimal: ',', separator: '.' },
  { code: 'BOB', label: 'BOB - BOLIVIANO', symbol: 'Bs.', decimal: '.', separator: ',' },
  { code: 'PYG', label: 'PYG - GUARANÍ PARAGUAYO', symbol: '₲', decimal: ',', separator: '.', precision: 0 },
  { code: 'GTQ', label: 'GTQ - QUETZAL GUATEMALTECO', symbol: 'Q', decimal: '.', separator: ',' },
  { code: 'CRC', label: 'CRC - COLÓN COSTARRICENSE', symbol: '₡', decimal: ',', separator: '.', precision: 0 },
  { code: 'DOP', label: 'DOP - PESO DOMINICANO', symbol: 'RD$', decimal: '.', separator: ',' },
  { code: 'NIO', label: 'NIO - CÓRDOBA NICARAGÜENSE', symbol: 'C$', decimal: '.', separator: ',' },
  { code: 'PAB', label: 'PAB - BALBOA PANAMEÑO', symbol: 'B/.', decimal: '.', separator: ',' },
  { code: 'HTG', label: 'HTG - GOURDE HAITIANO', symbol: 'G', decimal: '.', separator: ',' },
  { code: 'JMD', label: 'JMD - DÓLAR JAMAICANO', symbol: '$', decimal: '.', separator: ',' },
  { code: 'CUP', label: 'CUP - PESO CUBANO', symbol: '$', decimal: '.', separator: ',' },
  { code: 'SVC', label: 'SVC - COLÓN SALVADOREÑO', symbol: '₡', decimal: '.', separator: ',' },
  { code: 'VES', label: 'VES - BOLÍVAR VENEZOLANO', symbol: 'Bs.S', decimal: '.', separator: ',' },
  { code: 'SRD', label: 'SRD - DÓLAR SURINAMÉS', symbol: '$', decimal: '.', separator: ',' },
  { code: 'BZD', label: 'BZD - DÓLAR BELICEÑO', symbol: '$', decimal: '.', separator: ',' },
  { code: 'AWG', label: 'AWG - FLORÍN ARUBANO', symbol: 'ƒ', decimal: '.', separator: ',' },
  { code: 'ANG', label: 'ANG - FLORÍN ANTILLANO', symbol: 'ƒ', decimal: '.', separator: ',' },
  { code: 'XCD', label: 'XCD - DÓLAR DEL CARIBE ORIENTAL', symbol: '$', decimal: '.', separator: ',' },
  { code: 'BSD', label: 'BSD - DÓLAR BAHAMEÑO', symbol: '$', decimal: '.', separator: ',' },
  { code: 'BBD', label: 'BBD - DÓLAR BARBADIENSE', symbol: '$', decimal: '.', separator: ',' },
  { code: 'KYD', label: 'KYD - DÓLAR CAIMANÉS', symbol: '$', decimal: '.', separator: ',' },
  // Oriente Medio
  { code: 'AED', label: 'AED - DÍRHAM EMIRATÍ', symbol: 'د.إ', decimal: '.', separator: ',' },
  { code: 'SAR', label: 'SAR - RIYAL SAUDÍ', symbol: '﷼', decimal: '.', separator: ',' },
  { code: 'QAR', label: 'QAR - RIYAL CATARÍ', symbol: '﷼', decimal: '.', separator: ',' },
  { code: 'KWD', label: 'KWD - DINAR KUWAITÍ', symbol: 'KD', decimal: '.', separator: ',' },
  { code: 'OMR', label: 'OMR - RIAL OMANÍ', symbol: 'ر.ع.', decimal: '.', separator: ',' },
  { code: 'JOD', label: 'JOD - DINAR JORDANO', symbol: 'JD', decimal: '.', separator: ',' },
  { code: 'BHD', label: 'BHD - DINAR BAREINÍ', symbol: '.د.ب', decimal: '.', separator: ',' },
  { code: 'ILS', label: 'ILS - SÉQUEL ISRAELÍ', symbol: '₪', decimal: '.', separator: ',' },
  { code: 'IRR', label: 'IRR - RIAL IRANÍ', symbol: '﷼', decimal: '.', separator: ',' },
  { code: 'IQD', label: 'IQD - DINAR IRAQUÍ', symbol: 'ع.د', decimal: '.', separator: ',' },
  { code: 'YER', label: 'YER - RIAL YEMENÍ', symbol: '﷼', decimal: '.', separator: ',' },
  { code: 'LBP', label: 'LBP - LIBRA LIBANESA', symbol: 'ل.ل', decimal: '.', separator: ',' },
  { code: 'SYP', label: 'SYP - LIBRA SIRIA', symbol: '£', decimal: '.', separator: ',' },
  // Asia Oriental y Pacífico
  { code: 'CNY', label: 'CNY - YUAN CHINO', symbol: '¥', decimal: '.', separator: ',' },
  { code: 'HKD', label: 'HKD - DÓLAR DE HONG KONG', symbol: 'HK$', decimal: '.', separator: ',' },
  { code: 'TWD', label: 'TWD - DÓLAR DE TAIWÁN', symbol: 'NT$', decimal: '.', separator: ',' },
  { code: 'KRW', label: 'KRW - WON SURCOREANO', symbol: '₩', decimal: '.', separator: ',', precision: 0 },
  { code: 'KPW', label: 'KPW - WON NORCOREANO', symbol: '₩', decimal: '.', separator: ',', precision: 0 },
  { code: 'SGD', label: 'SGD - DÓLAR DE SINGAPUR', symbol: 'S$', decimal: '.', separator: ',' },
  { code: 'THB', label: 'THB - BAHT TAILANDÉS', symbol: '฿', decimal: '.', separator: ',' },
  { code: 'MYR', label: 'MYR - RINGGIT MALAYO', symbol: 'RM', decimal: '.', separator: ',' },
  { code: 'IDR', label: 'IDR - RUPIA INDONESIA', symbol: 'Rp', decimal: ',', separator: '.', precision: 0 },
  { code: 'PHP', label: 'PHP - PESO FILIPINO', symbol: '₱', decimal: '.', separator: ',' },
  { code: 'VND', label: 'VND - DONG VIETNAMITA', symbol: '₫', decimal: ',', separator: '.', precision: 0 },
  { code: 'KHR', label: 'KHR - RIEL CAMBOYANO', symbol: '៛', decimal: '.', separator: ',', precision: 0 },
  { code: 'LAK', label: 'LAK - KIP LAOSIANO', symbol: '₭', decimal: '.', separator: ',', precision: 0 },
  { code: 'MMK', label: 'MMK - KYAT BIRMANO', symbol: 'K', decimal: '.', separator: ',' },
  { code: 'BND', label: 'BND - DÓLAR BRUNEANO', symbol: '$', decimal: '.', separator: ',' },
  { code: 'MOP', label: 'MOP - PATACA MACAESA', symbol: 'P', decimal: '.', separator: ',' },
  // Asia Central y del Sur
  { code: 'INR', label: 'INR - RUPIA INDIA', symbol: '₹', decimal: '.', separator: ',' },
  { code: 'PKR', label: 'PKR - RUPIA PAKISTANÍ', symbol: '₨', decimal: '.', separator: ',' },
  { code: 'LKR', label: 'LKR - RUPIA ESRILANQUESA', symbol: '₨', decimal: '.', separator: ',' },
  { code: 'NPR', label: 'NPR - RUPIA NEPALESA', symbol: '₨', decimal: '.', separator: ',' },
  { code: 'BDT', label: 'BDT - TAKA BANGLADESÍ', symbol: '৳', decimal: '.', separator: ',' },
  { code: 'MVR', label: 'MVR - RUFIYAA MALDIVA', symbol: 'ރ', decimal: '.', separator: ',' },
  { code: 'BTN', label: 'BTN - NGULTRUM BUTANÉS', symbol: 'Nu.', decimal: '.', separator: ',' },
  { code: 'AFN', label: 'AFN - AFGANI', symbol: '؋', decimal: '.', separator: ',' },
  { code: 'KZT', label: 'KZT - TENGE KAZAJO', symbol: '₸', decimal: '.', separator: ',' },
  { code: 'UZS', label: 'UZS - SOM UZBEKO', symbol: 'лв', decimal: '.', separator: ',' },
  { code: 'KGS', label: 'KGS - SOM KIRGUÍS', symbol: 'с', decimal: '.', separator: ',' },
  { code: 'TJS', label: 'TJS - SOMONI TAYIKO', symbol: 'ЅМ', decimal: '.', separator: ',' },
  { code: 'TMT', label: 'TMT - MANAT TURCOMANO', symbol: 'T', decimal: '.', separator: ',' },
  { code: 'AMD', label: 'AMD - DRAM ARMENIO', symbol: '֏', decimal: '.', separator: ',' },
  { code: 'AZN', label: 'AZN - MANAT AZERBAIYANO', symbol: '₼', decimal: '.', separator: ',' },
  // Oceanía
  { code: 'NZD', label: 'NZD - DÓLAR NEOZELANDÉS', symbol: 'NZ$', decimal: '.', separator: ',' },
  { code: 'PGK', label: 'PGK - KINA PAPUANESA', symbol: 'K', decimal: '.', separator: ',' },
  { code: 'SBD', label: 'SBD - DÓLAR SALOMONENSE', symbol: '$', decimal: '.', separator: ',' },
  { code: 'WST', label: 'WST - TALA SAMOANO', symbol: 'T', decimal: '.', separator: ',' },
  { code: 'VUV', label: 'VUV - VATU VANUATENSE', symbol: 'Vt', decimal: '.', separator: ',', precision: 0 },
  { code: 'XPF', label: 'XPF - FRANCO CFP', symbol: 'Fr', decimal: '.', separator: ',', precision: 0 },
  // África
  { code: 'ZAR', label: 'ZAR - RAND SUDAFRICANO', symbol: 'R', decimal: '.', separator: ',' },
  { code: 'MAD', label: 'MAD - DÍRHAM MARROQUÍ', symbol: 'MAD', decimal: '.', separator: ',' },
  { code: 'EGP', label: 'EGP - LIBRA EGIPCIA', symbol: 'E£', decimal: '.', separator: ',' },
  { code: 'TND', label: 'TND - DINAR TUNECINO', symbol: 'DT', decimal: '.', separator: ',' },
  { code: 'DZD', label: 'DZD - DINAR ARGELINO', symbol: 'د.ج', decimal: '.', separator: ',' },
  { code: 'LYD', label: 'LYD - DINAR LIBIO', symbol: 'ل.د', decimal: '.', separator: ',' },
  { code: 'SDG', label: 'SDG - LIBRA SUDANESA', symbol: '£', decimal: '.', separator: ',' },
  { code: 'ETB', label: 'ETB - BIRR ETÍOPE', symbol: 'Br', decimal: '.', separator: ',' },
  { code: 'KES', label: 'KES - CHELÍN KENIANO', symbol: 'KSh', decimal: '.', separator: ',' },
  { code: 'TZS', label: 'TZS - CHELÍN TANZANO', symbol: 'TSh', decimal: '.', separator: ',', precision: 0 },
  { code: 'UGX', label: 'UGX - CHELÍN UGANDÉS', symbol: 'Sh', decimal: '.', separator: ',', precision: 0 },
  { code: 'NGN', label: 'NGN - NAIRA NIGERIANA', symbol: '₦', decimal: '.', separator: ',' },
  { code: 'GHS', label: 'GHS - CEDI GHANÉS', symbol: '₵', decimal: '.', separator: ',' },
  { code: 'XOF', label: 'XOF - FRANCO CFA OCCIDENTAL', symbol: 'Fr', decimal: '.', separator: ',', precision: 0 },
  { code: 'XAF', label: 'XAF - FRANCO CFA CENTROAFRICANO', symbol: 'Fr', decimal: '.', separator: ',', precision: 0 },
  { code: 'RWF', label: 'RWF - FRANCO RUANDÉS', symbol: 'Fr', decimal: '.', separator: ',', precision: 0 },
  { code: 'BIF', label: 'BIF - FRANCO BURUNDÉS', symbol: 'Fr', decimal: '.', separator: ',', precision: 0 },
  { code: 'KMF', label: 'KMF - FRANCO COMORANO', symbol: 'Fr', decimal: '.', separator: ',', precision: 0 },
  { code: 'CDF', label: 'CDF - FRANCO CONGOLEÑO', symbol: 'Fr', decimal: '.', separator: ',' },
  { code: 'DJF', label: 'DJF - FRANCO YIBUTIANO', symbol: 'Fr', decimal: '.', separator: ',', precision: 0 },
  { code: 'GNF', label: 'GNF - FRANCO GUINEANO', symbol: 'Fr', decimal: '.', separator: ',', precision: 0 },
  { code: 'MGA', label: 'MGA - ARIARY MALGACHE', symbol: 'Ar', decimal: '.', separator: ',', precision: 0 },
  { code: 'AOA', label: 'AOA - KUANZA ANGOLEÑO', symbol: 'Kz', decimal: '.', separator: ',' },
  { code: 'CVE', label: 'CVE - ESCUDO CABOVERDIANO', symbol: '$', decimal: '.', separator: ',' },
  { code: 'MZN', label: 'MZN - METICAL MOZAMBIQUEÑO', symbol: 'MT', decimal: '.', separator: ',' },
  { code: 'NAD', label: 'NAD - DÓLAR NAMIBIO', symbol: '$', decimal: '.', separator: ',' },
  { code: 'BWP', label: 'BWP - PULA DE BOTSUANA', symbol: 'P', decimal: '.', separator: ',' },
  { code: 'MWK', label: 'MWK - KUACHA MALAUÍ', symbol: 'MK', decimal: '.', separator: ',' },
  { code: 'ZMW', label: 'ZMW - KUACHA ZAMBIANO', symbol: 'ZK', decimal: '.', separator: ',' },
  { code: 'ZWL', label: 'ZWL - DÓLAR ZIMBABUENSE', symbol: '$', decimal: '.', separator: ',' },
  { code: 'LSL', label: 'LSL - LOTI LESOTENSE', symbol: 'L', decimal: '.', separator: ',' },
  { code: 'SZL', label: 'SZL - LILANGENI SUAZI', symbol: 'L', decimal: '.', separator: ',' },
  { code: 'LRD', label: 'LRD - DÓLAR LIBERIANO', symbol: '$', decimal: '.', separator: ',' },
  { code: 'SLL', label: 'SLL - LEONA SIERRALEONESA', symbol: 'Le', decimal: '.', separator: ',' },
  { code: 'GIP', label: 'GIP - LIBRA GIBRALTAREÑA', symbol: '£', decimal: '.', separator: ',' },
  { code: 'SOS', label: 'SOS - CHELÍN SOMALÍ', symbol: 'Sh', decimal: '.', separator: ',' },
  { code: 'SSP', label: 'SSP - LIBRA SURSUDANESA', symbol: '£', decimal: '.', separator: ',' },
  { code: 'ERN', label: 'ERN - NAKFA ERITREO', symbol: 'Nfk', decimal: '.', separator: ',' },
  { code: 'SCR', label: 'SCR - RUPIA SEYCHELLENSE', symbol: '₨', decimal: '.', separator: ',' },
  { code: 'STN', label: 'STN - DOBRA SANTOTOMENSE', symbol: 'Db', decimal: '.', separator: ',' },
];
